#!/bin/bash
# .husky/commit-msg

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

# Regex pour valider le format
commit_regex='^(feat|fix|docs|style|refactor|perf|test|chore|ci|build): .{1,150}$'

if ! echo "$commit_msg" | grep -qE "$commit_regex"; then
    echo "❌ Format de commit invalide !"
    echo ""
    echo "Format attendu : <type>: <description>"
    echo ""
    echo "Types valides :"
    echo "  feat, fix, docs, style, refactor, perf, test, chore, ci, build"
    echo ""
    echo "Exemples valides :"
    echo "  feat: ajouter la gestion des utilisateurs"
    echo "  fix: corriger l'erreur sur l’API"
    echo "  docs: mettre à jour le README"
    echo ""
    exit 1
fi

echo "✅ Format de commit valide !"
